import 'package:flutter_airbnb_ui/models/listing.dart';

const listings = [
  Listing(
    coverUrl: 'assets/images/listing-1.jpg',
    landlordAvatarUrl: 'assets/images/person-3.jpeg',
    landlordName: 'John',
    title: 'Bright apartment in vibrant neighborhood',
    address: 'Berlin, Germany',
    availability: 'May 9 - 14',
    rating: 4.79,
    reviewsCount: 200,
    price: 98,
  ),
  Listing(
    coverUrl: 'assets/images/listing-2.jpg',
    landlordAvatarUrl: 'assets/images/person-2.jpeg',
    landlordName: 'Jane',
    title: 'Quiet apartment outside the city',
    address: 'Paris, France',
    availability: 'May 9 - 14',
    rating: 4.5,
    reviewsCount: 400,
    price: 120,
  ),
  Listing(
    coverUrl: 'assets/images/listing-3.jpg',
    landlordAvatarUrl: 'assets/images/person-2.jpeg',
    landlordName: 'Jane',
    title: 'Quiet apartment outside the city',
    address: 'Paris, France',
    availability: 'May 9 - 14',
    rating: 4.5,
    reviewsCount: 400,
    price: 120,
  ),
  Listing(
    coverUrl: 'assets/images/listing-4.jpg',
    landlordAvatarUrl: 'assets/images/person-2.jpeg',
    landlordName: 'Jane',
    title: 'Quiet apartment outside the city',
    address: 'Paris, France',
    availability: 'May 9 - 14',
    rating: 4.5,
    reviewsCount: 400,
    price: 120,
  ),
  Listing(
    coverUrl: 'assets/images/listing-5.jpg',
    landlordAvatarUrl: 'assets/images/person-2.jpeg',
    landlordName: 'Jane',
    title: 'Quiet apartment outside the city',
    address: 'Paris, France',
    availability: 'May 9 - 14',
    rating: 4.5,
    reviewsCount: 400,
    price: 120,
  ),
  Listing(
    coverUrl: 'assets/images/listing-6.jpg',
    landlordAvatarUrl: 'assets/images/person-2.jpeg',
    landlordName: 'Jane',
    title: 'Quiet apartment outside the city',
    address: 'Paris, France',
    availability: 'May 9 - 14',
    rating: 4.5,
    reviewsCount: 400,
    price: 120,
  ),
];
